ERROR_PASSWORD_CONFIRM_NOT_IDENTICAL = 'password confirm not identical'
CODE_ERROR_PASSWORD_CONFIRM_NOT_IDENTICAL = 1

ERROR_USERNAME_MUST_BE_SET = 'username must be set'
CODE_ERROR_USERNAME_MUST_BE_SET = 2

ERROR_ALREADY_EXIST_USERNAME = 'already exsit username'
CODE_ERROR_ALREADY_EXIST_USERNAME = 3

ERROR_NOT_EXIST_ID = 'id is not exist'
CODE_ERROR_NOT_EXIST_ID = 4

ERROR_PASSWORD_NOT_CORRECT = 'password not correct'
CODE_ERROR_PASSWORD_NOT_CORRECT = 5

ERROR_NOT_ACTIVE_USER = 'not active user'
CODE_ERROR_NOT_ACTIVE_USER = 6